@startuml Architecture diagram for wuhan2020 project
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

'LAYOUT_WITH_LEGEND()
'LAYOUT_AS_SKETCH()

title

    <u> wuhan2020架构图 </u>

end title

Person(volunteer, "志愿者")


    System(shimo, "石墨", "表格收集")
    System(github, "wuhan2020/wuhan2020", "Yaml")


System_Boundary(data, "wuhan2020/数据同步"){
    System(dataFetcher, "数据收集", "")
    System_Boundary(dataParser, "数据解析"){
        System_Ext(pluginYML, "YAML 插件")
        System_Ext(pluginXML, "XML 插件")
        System_Ext(pluginCVS, "CVS 插件")
        System_Ext(pluginJSON, "JSON 插件")
        System_Ext(pluginOther, "其他")
    }
    System(dataExport, "数据发布", "")
}

System_Boundary(web, "wuhan2020/网站服务器"){
    System_Boundary(api, "Rest-API 服务器"){
        System(apiMap, "地图 API", "")
        System(apiWeb, "网页 API", "")
    }
    System(front, "网页前端", "")
}

Rel(volunteer, shimo, "填写")
Rel(shimo, dataFetcher, "收集")
Rel(dataFetcher, dataParser, "解析")
Rel(dataParser, dataExport, "发布")
Rel(dataExport, github, "YAML 更新")
Rel(apiWeb, github, "获取 YAML")
Rel(front, api, "渲染")
Rel(apiMap, dataExport, "获取 JSON")

center footer Architecture diagram for wuhan2020 project

@enduml


